services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      frontend:
        condition: service_started
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parol
      POSTGRES_DB: vizitka
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "parol"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
